Js homepage
cse110-fa22-group26/cse110-fa22-group26 pull request #35
Opened 2022-11-22 01:08 UTC by shangfucheng

Basically finished all local storage functionality, will need to update CSS file later.

2022-11-22 11:42 UTC, w3dong requested changes
GREAT JOB Y'ALL!!!! All functionality we asked for are completed nicely, not to mention the codes itself looks clear and simple. It looks great, but I believe that there are still a few things we can do for improvement: 
1) I see that you guys are also saving the status of checkbox for each task div, which is great and definitely sth we want to have, but for now it's not working as task["checkbox"] is not updated after clicks. You may need to create another function, like what we have done with icon functionality, to take care of checkbox.
2) Some missing param and 1 non-match method headers & add more inline comments
3) delete unused codes
*Optional if running out of time*
4) try to use array of 7 array data structure for savedTasks. This will help optimize runtime for  functions. After doing so, we can just go over tasks for specific weekday's list rather than go through the all tasks in weekly planner to change its data in localStorage. (Also we are using this structure in login-sign up page, this will make easier to connect all things together) 
 
Here are some implementation suggestion you may consider to follow: 
**addTasksToDocument():** we can just go through each list once (savedTasks[i])and add object inside to corresponding weekday div (document.getElementsByClassName("task-board")[0] === div with id="Monday"). 
**For helper functions**, we do need additional index mapping ("monday" => 0, "tuesday" => 1) function that help us get certain weekday's list. 
**For other functions**, we just need to assign tasks = getTasksFromStorage(), and then find certain weekday list by index by let localTasks = tasks[index]. Remember to save the tasks in localStorage rather than localTasks in this turn. 

Except for that, as functionality for add, delete, and confirm has completed, feel free to assign other team members to set up unit testing & E2E tests for the home page functions. Let us know if you need additional people to help: we can reassign people from log-in sign-up

2022-11-22 16:31 UTC, shangfucheng commented
Fixed all issue addressed above, please check when have time. thank you

2022-11-22 21:01 UTC, w3dong commented on source/assets/scripts/main.js
> +
Not being able to test it out.

2022-11-22 21:39 UTC, shangfucheng commented on source/assets/scripts/main.js
> +    return JSON.parse(localStorage.getItem('savedTasks')) || [];
fixed, you may need to clean old localStorage since they are different format.

2022-11-22 21:51 UTC, w3dong commented on source/assets/scripts/main.js
> +    return JSON.parse(localStorage.getItem('savedTasks')) || [];
Yes it is fixed! Nice job!

My bad, I guess the error was generated by inconsistency in localStorage. Thanks for pointing that out!

2022-11-23 04:15 UTC, w3dong reviewed
1. Checkbox storage bug
2. style adds on

2022-11-26 19:46 UTC, sepehrheravi commented
this has been extended by #47; we are going to close this pull request use #47 instead

2022-11-26 19:46 UTC, closed without merging